apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-configmap
data:
  nginx.conf: |
    worker_processes  1;
    
    events {
      worker_connections  1024;
    }
    
    http {
      upstream app1 {
        server app1-service:80;
      }
    
      upstream app2 {
        server app2-service:80;
      }
    
      server {
        listen 80;
    
        location /app1 {
          proxy_pass http://app1/;
        }
    
        location /app2 {
          proxy_pass http://app2/;
        }
      }
    }
