apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1-deployment
spec:
  selector:
    matchLabels:
      app: app1
  replicas: 1
  template:
    metadata:
      labels:
        app: app1
    spec:
      containers:
        - name: app1-container
          image: l3r4639/app1:latest
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: app1-configmap
      nodeSelector:
        app: app1
